### ISSUE TITLE
Обьявляете __str__ - а потом его же и вызываете  

### ISSUE THREAD

**Issue by Muxamedin** [v-kostyukov/ithillel-Introduction-Python#6]
https://github.com/v-kostyukov/ithillel-Introduction-Python/blob/45d2b82795646b993fd7da1b30d5066991870185/HW12/exception_class.py#L19

__str__  - если вы определяете метод этот в классе  то  объэкт этого класса при попытке привести его к строка
вызовет  этот метод __str__

print() - выполняет преобразование к строке параметров которые он получает
то в таком. случае вместо 
 print(error.__str__())
 досточно вызвать 
  print(error)

**Comment by v-kostyukov** [comment]
Изменил print(error.__str__()) на print(error)
https://github.com/v-kostyukov/ithillel-Introduction-Python/blob/main/HW12/exception_class.py

**Comment by Muxamedin** [comment]
.
