### ISSUE TITLE
input возвращает нам строку - зачем опть приводить к строке строку?

### ISSUE THREAD

**Issue by Muxamedin** [v-kostyukov/ithillel-Introduction-Python#7]
https://github.com/v-kostyukov/ithillel-Introduction-Python/blob/45d2b82795646b993fd7da1b30d5066991870185/HW12/exception_handling.py#L9
a , b  и так уже являются строками - нужно ли нам дополнительное преобразование строки в строку ?

**Comment by v-kostyukov** [comment]
Если мы ввели одно численное значение и не будем преобразовывать в строку при конкатенации то будет ошибка:
Введите 1 значение: 123
Введите 2 значение: asd
Traceback (most recent call last):
  File "C:/pythonProject/ithillel-Introduction-Python/HW12/exception_handling.py", line 7, in exception
    b = int(b)
ValueError: invalid literal for int() with base 10: 'asd'

TypeError: sequence item 0: expected str instance, int found

**Comment by Muxamedin** [comment]
Понял - если первым будет число то оно успеет преобразоваться в целосленное 
а  а если второе не число то получим исключение 

Тогда либо приводить к int но создавать новую переменную 
a_int = int(a)
b_int = int(b)
и не приводить к строке в теле исключения 

либо в теле исключения 
приводить к строке только первое значение
